#######################################
############  usuário  ################
#######################################

# Criar usuário
POST http://127.0.0.1:8000/usuario HTTP/1.1
content-type: application/json

{
    "id": 4,
    "nome": "teste 4",
    "email": "teste_4@outlook.com",
    "senha": "123456"
}

#######################################
# Pegar usuário
GET http://127.0.0.1:8000/usuario?id=4 HTTP/1.1
content-type: application/json

#############################################
# Pegar usuário pelo nome
GET http://127.0.0.1:8000/usuario/nome?nome=teste 4 HTTP/1.1
content-type: application/json

#######################################
# Pegar endereços do usuário
GET http://127.0.0.1:8000/usuario/4/enderecos HTTP/1.1
content-type: application/json

#############################################
# Deletar usuário pelo id
DELETE http://127.0.0.1:8000/usuario?id=4 HTTP/1.1
content-type: application/json

#############################################
# Pegar e-mails com o mesmo domínio
GET http://127.0.0.1:8000/usuarios/emails/?dominio=outlook.com HTTP/1.1
content-type: application/json

#######################################
############  endereço  ###############
#######################################

# Criar endereço
POST http://127.0.0.1:8000/endereco/4 HTTP/1.1
content-type: application/json


{
    "id": 2,
    "rua": "Rua x",
    "cep": "99999-999",
    "cidade": "Paraíba",
    "estado": "PB"
}

#############################################
# Deletar endereço
DELETE http://127.0.0.1:8000/usuario/4/endereco/1 HTTP/1.1
content-type: application/json


#######################################
############  produto  ################
#######################################

# Criar produto
POST http://127.0.0.1:8000/produto HTTP/1.1
content-type: application/json

{
    "id": 10,
    "nome": "Picolé",
    "descricao": "Doce gelado",
    "preco": 5.99
}


#############################################
# Deletar produto pelo id
DELETE http://127.0.0.1:8000/produto/6/ HTTP/1.1
content-type: application/json

#######################################
############  carrinho  ###############
#######################################

#############################################
# Adicionar ao carrinho
POST http://127.0.0.1:8000/carrinho/4/10/ HTTP/1.1
content-type: application/json

#############################################
# Retornar carrinho
GET http://127.0.0.1:8000/carrinho/4/ HTTP/1.1
content-type: application/json

#############################################
# Retornar total e quantidade de produtos no carrinho
GET http://127.0.0.1:8000/carrinho/total/4/ HTTP/1.1
content-type: application/json

#############################################
# Deletar carrinho do usuário
DELETE http://127.0.0.1:8000/carrinho/3/ HTTP/1.1
content-type: application/json


